default_platform(:ios)

platform :ios do

  lane :build_and_test do
    scan(
      project: './WildAnalyticsSDK.xcodeproj',
      prelaunch_simulator: true,
      clean: true,
      only_testing: 'WildAnalyticsSDKTests'
    )
  end
end
